[package]
name = "as_bit_mask_derive"
version = "0.1.0"
authors = ["paul fornage <paul@fornage.net>"]
keywords = ["template", "proc_macro", "procmacro"]
edition = "2024"

[lib]
proc-macro = true
doctest = false

[dependencies]
quote = "1"
syn = "^2.0.0"

